// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PropertyMatch.API.Data;

#nullable disable

namespace PropertyMatch.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PropertyMatch.API.Models.Agent", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContactNo")
                        .HasColumnType("text");

                    b.Property<string>("LicenseNumber")
                        .HasColumnType("text");

                    b.Property<decimal?>("Ratings")
                        .HasColumnType("numeric");

                    b.Property<string>("StripeCustomerId")
                        .HasColumnType("text");

                    b.Property<int>("TokenBalance")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.ToTable("Agents", (string)null);
                });

            modelBuilder.Entity("PropertyMatch.API.Models.AvailabilityException", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EndTime")
                        .HasColumnType("text");

                    b.Property<DateTime>("ExceptionFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExceptionTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ListingId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<string>("StartTime")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ListingId");

                    b.HasIndex("AgentId", "ListingId")
                        .HasDatabaseName("IX_AvailabilityExceptions_AgentId_ListingId");

                    b.HasIndex("ExceptionFrom", "ExceptionTo")
                        .HasDatabaseName("IX_AvailabilityExceptions_ExceptionFrom_ExceptionTo");

                    b.ToTable("AvailabilityExceptions", (string)null);
                });

            modelBuilder.Entity("PropertyMatch.API.Models.AvailabilityTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<string>("EndTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ListingId")
                        .HasColumnType("uuid");

                    b.Property<int>("SlotDurationMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(60);

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DayOfWeek")
                        .HasDatabaseName("IX_AvailabilityTemplates_DayOfWeek");

                    b.HasIndex("ListingId");

                    b.HasIndex("AgentId", "ListingId")
                        .HasDatabaseName("IX_AvailabilityTemplates_AgentId_ListingId");

                    b.ToTable("AvailabilityTemplates", (string)null);
                });

            modelBuilder.Entity("PropertyMatch.API.Models.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AgentLastReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastMessageAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("TenantLastReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("ListingId");

                    b.HasIndex("TenantId", "ListingId")
                        .IsUnique();

                    b.ToTable("Conversations", (string)null);
                });

            modelBuilder.Entity("PropertyMatch.API.Models.EmailVerification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("EmailVerifications", (string)null);
                });

            modelBuilder.Entity("PropertyMatch.API.Models.FavouriteListing", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SavedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TenantId", "ListingId");

                    b.HasIndex("ListingId");

                    b.ToTable("FavouriteListings", (string)null);
                });

            modelBuilder.Entity("PropertyMatch.API.Models.Feedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Feedbacks", (string)null);
                });

            modelBuilder.Entity("PropertyMatch.API.Models.LifestyleTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<List<string>>("PlaceTypes")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("LifestyleTemplates", (string)null);
                });

            modelBuilder.Entity("PropertyMatch.API.Models.Listing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Amenities")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<double>("Lat")
                        .HasColumnType("double precision");

                    b.Property<double>("Lng")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("ResidencyType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rooms")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Toilets")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("Status");

                    b.ToTable("Listings", (string)null);
                });

            modelBuilder.Entity("PropertyMatch.API.Models.ListingImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Caption")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid");

                    b.Property<string>("S3Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ListingId");

                    b.ToTable("ListingImages", (string)null);
                });

            modelBuilder.Entity("PropertyMatch.API.Models.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.Property<string>("SenderRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages", (string)null);
                });

            modelBuilder.Entity("PropertyMatch.API.Models.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("StripePaymentIntentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StripeSessionId")
                        .HasColumnType("text");

                    b.Property<int>("TokensPurchased")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("PropertyMatch.API.Models.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Item")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Reports", (string)null);
                });

            modelBuilder.Entity("PropertyMatch.API.Models.Reviews", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Ratings")
                        .HasColumnType("numeric");

                    b.Property<string>("ReviewText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("TenantId");

                    b.ToTable("Reviews", (string)null);
                });

            modelBuilder.Entity("PropertyMatch.API.Models.ScoringConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LifestyleRadiusMeters")
                        .HasColumnType("integer");

                    b.Property<double>("WeightCommute")
                        .HasColumnType("double precision");

                    b.Property<double>("WeightLifestyle")
                        .HasColumnType("double precision");

                    b.Property<double>("WeightNumeric")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("ScoringConfig", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LifestyleRadiusMeters = 800,
                            WeightCommute = 0.29999999999999999,
                            WeightLifestyle = 0.29999999999999999,
                            WeightNumeric = 0.40000000000000002
                        });
                });

            modelBuilder.Entity("PropertyMatch.API.Models.SearchLog", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SearchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Snapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TenantId", "SearchedAt");

                    b.ToTable("SearchLogs", (string)null);
                });

            modelBuilder.Entity("PropertyMatch.API.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("PropertyMatch.API.Models.ViewHistory", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ViewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TenantId", "ListingId", "ViewedAt");

                    b.HasIndex("ListingId");

                    b.ToTable("ViewHistory", (string)null);
                });

            modelBuilder.Entity("PropertyMatch.API.Models.ViewingSchedule", b =>
                {
                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("ListingId", "ScheduledAt");

                    b.HasIndex("TenantId");

                    b.ToTable("ViewingSchedules", (string)null);
                });

            modelBuilder.Entity("PropertyMatch.API.Models.Agent", b =>
                {
                    b.HasOne("PropertyMatch.API.Models.User", "User")
                        .WithOne("Agent")
                        .HasForeignKey("PropertyMatch.API.Models.Agent", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PropertyMatch.API.Models.AvailabilityException", b =>
                {
                    b.HasOne("PropertyMatch.API.Models.Agent", "Agent")
                        .WithMany("AvailabilityExceptions")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PropertyMatch.API.Models.Listing", "Listing")
                        .WithMany("AvailabilityExceptions")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Agent");

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("PropertyMatch.API.Models.AvailabilityTemplate", b =>
                {
                    b.HasOne("PropertyMatch.API.Models.Agent", "Agent")
                        .WithMany("AvailabilityTemplates")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PropertyMatch.API.Models.Listing", "Listing")
                        .WithMany("AvailabilityTemplates")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Agent");

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("PropertyMatch.API.Models.Conversation", b =>
                {
                    b.HasOne("PropertyMatch.API.Models.Agent", "Agent")
                        .WithMany("Conversations")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PropertyMatch.API.Models.Listing", "Listing")
                        .WithMany("Conversations")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PropertyMatch.API.Models.User", "Tenant")
                        .WithMany("Conversations")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Listing");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PropertyMatch.API.Models.EmailVerification", b =>
                {
                    b.HasOne("PropertyMatch.API.Models.User", "User")
                        .WithMany("EmailVerifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PropertyMatch.API.Models.FavouriteListing", b =>
                {
                    b.HasOne("PropertyMatch.API.Models.Listing", "Listing")
                        .WithMany("FavouritedBy")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PropertyMatch.API.Models.User", "Tenant")
                        .WithMany("FavouriteListings")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PropertyMatch.API.Models.Feedback", b =>
                {
                    b.HasOne("PropertyMatch.API.Models.User", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PropertyMatch.API.Models.LifestyleTemplate", b =>
                {
                    b.HasOne("PropertyMatch.API.Models.User", "Tenant")
                        .WithMany("LifestyleTemplates")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PropertyMatch.API.Models.Listing", b =>
                {
                    b.HasOne("PropertyMatch.API.Models.Agent", "Agent")
                        .WithMany("Listings")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("PropertyMatch.API.Models.ListingImage", b =>
                {
                    b.HasOne("PropertyMatch.API.Models.Listing", "Listing")
                        .WithMany("Images")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("PropertyMatch.API.Models.Message", b =>
                {
                    b.HasOne("PropertyMatch.API.Models.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PropertyMatch.API.Models.User", "Sender")
                        .WithMany("SentMessages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("PropertyMatch.API.Models.Payment", b =>
                {
                    b.HasOne("PropertyMatch.API.Models.Agent", "Agent")
                        .WithMany("Payments")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("PropertyMatch.API.Models.Report", b =>
                {
                    b.HasOne("PropertyMatch.API.Models.User", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PropertyMatch.API.Models.Reviews", b =>
                {
                    b.HasOne("PropertyMatch.API.Models.Agent", "Agent")
                        .WithMany("Reviews")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PropertyMatch.API.Models.User", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PropertyMatch.API.Models.SearchLog", b =>
                {
                    b.HasOne("PropertyMatch.API.Models.User", "Tenant")
                        .WithMany("SearchLogs")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PropertyMatch.API.Models.ViewHistory", b =>
                {
                    b.HasOne("PropertyMatch.API.Models.Listing", "Listing")
                        .WithMany("ViewHistory")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PropertyMatch.API.Models.User", "Tenant")
                        .WithMany("ViewHistory")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PropertyMatch.API.Models.ViewingSchedule", b =>
                {
                    b.HasOne("PropertyMatch.API.Models.Listing", "Listing")
                        .WithMany("ViewingSchedules")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PropertyMatch.API.Models.User", "Tenant")
                        .WithMany("ViewingSchedules")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PropertyMatch.API.Models.Agent", b =>
                {
                    b.Navigation("AvailabilityExceptions");

                    b.Navigation("AvailabilityTemplates");

                    b.Navigation("Conversations");

                    b.Navigation("Listings");

                    b.Navigation("Payments");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("PropertyMatch.API.Models.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("PropertyMatch.API.Models.Listing", b =>
                {
                    b.Navigation("AvailabilityExceptions");

                    b.Navigation("AvailabilityTemplates");

                    b.Navigation("Conversations");

                    b.Navigation("FavouritedBy");

                    b.Navigation("Images");

                    b.Navigation("ViewHistory");

                    b.Navigation("ViewingSchedules");
                });

            modelBuilder.Entity("PropertyMatch.API.Models.User", b =>
                {
                    b.Navigation("Agent");

                    b.Navigation("Conversations");

                    b.Navigation("EmailVerifications");

                    b.Navigation("FavouriteListings");

                    b.Navigation("LifestyleTemplates");

                    b.Navigation("SearchLogs");

                    b.Navigation("SentMessages");

                    b.Navigation("ViewHistory");

                    b.Navigation("ViewingSchedules");
                });
#pragma warning restore 612, 618
        }
    }
}
